AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infrastructure Alarm Stack

Mappings:
  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  SNSAlarmTopicNameMap:
    test:
      name: test-alarm-topic
    stage:
      name: stage-alarm-topic
    prod:
      name: prod-alarm-topic

  FunctionName:
    AlarmSenderFunction:
      test: test-alarm-sender-infrastructure
      stage: stage-alarm-sender-infrastructure
      prod: prod-alarm-sender-infrastructure

  SlackWebhookUrlMap:
    WebhookUrl:
      test: "https://hooks.slack.com/services/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"
      stage: "https://hooks.slack.com/services/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"
      prod: "https://hooks.slack.com/services/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"


Parameters:

  Env:
    Type: String
    AllowedValues:
      - stage
      - prod
      - test
    Default: stage
    Description: Enter env name

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: go1.x
    Environment:
      Variables:
        ENV: !Ref Env
        PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
        SLACK_WEBHOOK_URL: !FindInMap [SlackWebhookUrlMap, WebhookUrl, !Ref Env]
    Tags:
      Company: Ringoid
      Service: infrastructure
      Environment: !Ref Env

Resources:

  AlarmSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, AlarmSenderFunction, !Ref Env]
      Handler: alarm_sender
      CodeUri: ./alarm_sender.zip
      Description: Handle sns alarm
      Events:
        StartEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSAlarmTopic

  SNSAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !FindInMap [SNSAlarmTopicNameMap, !Ref Env, name]
      TopicName: !FindInMap [SNSAlarmTopicNameMap, !Ref Env, name]

Outputs:
  SNSAlarmTopicOutput:
    Value: !Ref SNSAlarmTopic
    Export:
      Name: !Join [ "-", [ !Ref Env, SNSAlarmTopicExport] ]
