AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alarm Stack

Mappings:
  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      prod: "should-be-prod-papertril-endpoint"

  SNSAlarmTopicNameMap:
    stage:
      name: stage-alarm-topic
    prod:
      name: prod-alarm-topic

  FunctionName:
    AlarmSenderFunction:
      stage: stage-alarm-sender-infrastructure
      prod: prod-alarm-sender-infrastructure


Parameters:

  Env:
    Type: String
    AllowedValues:
      - stage
      - prod
    Default: stage
    Description: Enter env name

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: go1.x
    Environment:
      Variables:
        ENV: !Ref Env
        PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
    Tags:
      Company: Ringoid
      Service: infrastructure
      Environment: !Ref Env

Resources:

  AlarmSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, AlarmSenderFunction, !Ref Env]
      Handler: alarm_sender
      CodeUri: ./alarm_sender.zip
      Description: Handle sns alarm
      Events:
        StartEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSAlarmTopic

  SNSAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !FindInMap [SNSAlarmTopicNameMap, !Ref Env, name]
      TopicName: !FindInMap [SNSAlarmTopicNameMap, !Ref Env, name]

Outputs:
  SNSAlarmTopicOutput:
    Value: !Ref SNSAlarmTopic
    Export:
      Name: !Join [ "-", [ !Ref Env, SNSAlarmTopicExport] ]
