AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure Common Stream Stack

Mappings:
  CommonStreamNameMap:
    test:
      name: test-CommonEventStream
    stage:
      name: stage-CommonEventStream
    prod:
      name: prod-CommonEventStream

  InternalStreamNameMap:
    test:
      name: test-InternalEventStream
    stage:
      name: stage-InternalEventStream
    prod:
      name: prod-InternalEventStream


Parameters:

  Env:
    Type: String
    AllowedValues:
      - stage
      - prod
      - test
    Default: stage
    Description: Enter env name

Resources:

  CommonEventStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ "-", [ !Ref Env, CommonEventStream] ]
      RetentionPeriodHours: 24
      ShardCount: 1
      Tags:
        - Key: Company
          Value: Ringoid
        - Key: Environment
          Value: !Ref Env
        - Key: Service
          Value: infrastructure

  InternalEventStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ "-", [ !Ref Env, InternalEventStream] ]
      RetentionPeriodHours: 24
      ShardCount: 1
      Tags:
        - Key: Company
          Value: Ringoid
        - Key: Environment
          Value: !Ref Env
        - Key: Service
          Value: infrastructure


Outputs:
  CommonEventStreamExport:
    Value:
      Fn::GetAtt:
        - CommonEventStream
        - Arn
    Export:
      Name: !Join [ "-", [ !Ref Env, CommonEventStreamExport] ]
  CommonEventStreamNameExport:
    Value: !FindInMap [CommonStreamNameMap, !Ref Env, name]
    Export:
      Name: !Join [ "-", [ !Ref Env, CommonEventStreamExportName] ]
  InternalEventStreamExport:
    Value:
      Fn::GetAtt:
        - InternalEventStream
        - Arn
    Export:
      Name: !Join [ "-", [ !Ref Env, InternalEventStreamExport] ]
  InternalEventStreamNameExport:
    Value: !FindInMap [InternalStreamNameMap, !Ref Env, name]
    Export:
      Name: !Join [ "-", [ !Ref Env, InternalEventStreamExportName] ]
